[package]
name = "neutrondb-rs-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neutrondb = { path = "../neutrondb-rs" }
opis = "5.7.0"
blake3 = "1.5.0"
rand = "0.8"
